sonar.projectName=CloudScope
sonar.sourceEncoding=UTF-8
sonar.sources=CLOUDSCOPE/cloudscope-frontend/src,CLOUDSCOPE/cloudscope-backend/src/main/java
sonar.tests=CLOUDSCOPE/cloudscope-frontend/tests,CLOUDSCOPE/cloudscope-backend/src/test/java
sonar.java.source=21
sonar.java.binaries=CLOUDSCOPE/cloudscope-backend/target/classes
sonar.java.test.binaries=CLOUDSCOPE/cloudscope-backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=CLOUDSCOPE/cloudscope-backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=CLOUDSCOPE/cloudscope-frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**
